name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Install Awesome Bot
        run: gem install awesome_bot
      - name: Run Awesome Bot
        run: awesome_bot README.md --allow-redirect --allow-timeout -t 5 --request-delay 0.5 --allow-dupe
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ab-results
          path: ab-results-README.md-filtered.json
